# Generated by Django 4.2.2 on 2023-07-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinelearningapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecontent',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='enrollment',
            name='enrolled',
            field=models.BooleanField(default=False),
        ),
    ]
